### ISSUE TITLE
pageflow-chart plugin: wiki page errors

### ISSUE THREAD

**Issue by thy1985** [codevise/pageflow-chart#4]
Pull request for typos below: #3 

Just a few remarks to:
https://github.com/codevise/pageflow-chart
a)
gem 'pagflow-chart'
=>
-e missing
b)
Mutiple .scss.css that should be .css.scss
(same for https://github.com/codevise/pageflow-embedded-video)

bundle install missing before install + run migrations

**Comment by tf** [comment]
Thanks. No separate issue required though. The PR is all that's needed.

**Comment by thy1985** [comment]
okay, so I know that for the future.
